# Generated by Django 4.0.6 on 2022-11-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdno', models.IntegerField()),
                ('stdname', models.CharField(max_length=50)),
                ('stdmarks', models.FloatField()),
                ('stdresult', models.CharField(max_length=255)),
            ],
        ),
    ]
